spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/realjpa
    username: sa
    password:
    driver-class-name:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
#Global Setting
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
        one-indexed-parameters: true

logging.level:
  org.hibernate.SQL: debug
